config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('catalog.urls', namespace='catalog')),
    path('user/', include('users.urls', namespace='users')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/urls.py
from django.urls import path

from users.apps import UsersConfig
from users.views import LoginView, LogoutView, RegisterView, VerifiedSentView, verify_email, ProfileView, \
    generate_new_password

app_name = UsersConfig.name

urlpatterns = [
    path('login/', LoginView.as_view(), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('register/', RegisterView.as_view(), name='register'),
    path('register/verified_sent/', VerifiedSentView.as_view(), name='verified_sent'),
    path('verify_email/<str:uidb64>/<str:token>/', verify_email, name='verify_email'),
    path('profile', ProfileView.as_view(), name='profile'),
    path('profile/genpassword', generate_new_password, name='generate_new_password'),
]

users/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models

from catalog.models import NULLABLE


class User(AbstractUser):
    username = None
    email = models.EmailField(unique=True, verbose_name='почта')

    avatar = models.ImageField(upload_to='users/', verbose_name='аватар', **NULLABLE)
    phone = models.CharField(max_length=35, verbose_name='номер телефона', **NULLABLE)
    country = models.CharField(max_length=50, verbose_name='страна', **NULLABLE)

    USERNAME_FIELD = "email"
    REQUIRED_FIELDS = []

    class Meta:
        verbose_name = 'пользователь'
        verbose_name_plural = 'пользователи'

users/forms.py
from django.contrib.auth.forms import AuthenticationForm, UserCreationForm, UserChangeForm
from django import forms
from catalog.forms import StyleFormMixin
from users.models import User


class LoginForm(StyleFormMixin, AuthenticationForm):

    class Meta:
        model = User


class RegisterForm(StyleFormMixin, UserCreationForm):

    class Meta:
        model = User
        fields = ('email', 'password1', 'password2')


class ProfileForm(StyleFormMixin, UserChangeForm):

    class Meta:
        model = User
        fields = ('email', 'first_name', 'last_name', 'phone', 'avatar', 'country')

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

        self.fields['password'].widget = forms.HiddenInput()

users/views.py
import random

from django.conf import settings
from django.contrib.auth import login
from django.contrib.auth.tokens import default_token_generator
from django.contrib.auth.views import LoginView as BaseLoginView
from django.contrib.auth.views import LogoutView as BaseLogoutView
from django.contrib.sites.models import Site
from django.core.mail import send_mail
from django.shortcuts import redirect
from django.urls import reverse_lazy, reverse
from django.utils.encoding import force_bytes, force_str
from django.utils.http import urlsafe_base64_encode, urlsafe_base64_decode
from django.views.generic import CreateView, TemplateView, UpdateView

from users.forms import LoginForm, RegisterForm, ProfileForm
from users.models import User


class LoginView(BaseLoginView):
    model = User
    form_class = LoginForm
    template_name = 'users/login.html'


class LogoutView(BaseLogoutView):
    pass


class RegisterView(CreateView):
    model = User
    form_class = RegisterForm
    template_name = 'users/register.html'
    extra_context = {'title': "Регистрация Safyro's Market"}

    def form_valid(self, form):
        user = form.save()
        user.is_active = False
        user.save()
        token = default_token_generator.make_token(user)
        uid = urlsafe_base64_encode(force_bytes(user.pk))
        activation_url = reverse_lazy('users:verify_email', kwargs={'uidb64': uid, 'token': token})
        current_site = Site.objects.get_current()

        send_mail(
            subject='Подтвердите свой электронный адрес',
            message=f'Пожалуйста, перейдите по следующей ссылке, чтобы подтвердить свой адрес электронной почты: '
            f'http://{current_site}{activation_url}',
            from_email=settings.EMAIL_HOST_USER,
            recipient_list=[user.email],
            fail_silently=False,
        )
        return redirect('users:verified_sent')


def verify_email(request, uidb64, token):
    try:
        uid = force_str(urlsafe_base64_decode(uidb64))
        user = User.objects.get(pk=uid)
    except (TypeError, ValueError, OverflowError, User.DoesNotExist):
        user = None

    if user is not None and default_token_generator.check_token(user, token):
        user.is_active = True
        user.save()
        login(request, user)
        return redirect('catalog:product_list')
    else:
        return redirect('users:login')


class VerifiedSentView(TemplateView):
    template_name = 'users/verified_sent.html'
    extra_context = {
        'title': "Подтверждение почты Safyro's Market"
    }


class ProfileView(UpdateView):
    model = User
    form_class = ProfileForm
    success_url = 'users:profile'
    extra_context = {'title': "Редактирование профиля Safyro's Market"}

    def get_object(self, queryset=None):
        return self.request.user


def generate_new_password(request):
    new_password = ''.join([str(random.randint(0, 9)) for _ in range(12)])
    send_mail(
        subject='Вы сменили пароль',
        message=f'Ваш новый пароль: {new_password}',
        from_email=settings.EMAIL_HOST_USER,
        recipient_list=[request.user.email]
    )
    request.user.set_password(new_password)
    request.user.save()
    return redirect(reverse('catalog:product_list'))

users/templates/users/login.html
{% extends 'catalog/base.html' %}
{% load my_tags %}
{% block content %}
    <div class="container">
        <div class="row mt-5">
            <div class="col-3"></div>
            <div class="col-6 mt-5">
                <div class="card">
                <div class="card-header mx-auto">
                    <div class="card-title">
                        <h3>Вход</h3>
                    </div>
                </div>
                    <div class="card-body">
                        <form method="post" enctype="multipart/form-data">
                            {% csrf_token %}
                            {{ form.as_p }}
                            <button type="submit" class="btn btn-outline-primary float-right">
                                Войти
                            </button>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

users/templates/users/register.html
{% extends 'catalog/base.html' %}
{% load my_tags %}
{% block content %}
    <div class="container">
        <div class="row mt-5">
            <div class="col-3"></div>
            <div class="col-6 mt-5">
                <div class="card">
                <div class="card-header mx-auto">
                    <div class="card-title">
                        <h3>Регистрация</h3>
                    </div>
                </div>
                    <div class="card-body">
                        <form method="post" enctype="multipart/form-data">
                            {% csrf_token %}
                            {{ form.as_p }}
                            <button type="submit" class="btn btn-outline-primary float-right">
                                Зарегистрироваться
                            </button>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

users/templates/users/user_form.html
{% extends 'catalog/base.html' %}
{% load my_tags %}
{% block content %}
    <div class="container">
        <div class="row mt-5">
            <div class="col-3"></div>
            <div class="col-6 mt-5">
                <div class="card">
                    <div class="card-header mx-auto">
                        <div class="card-title">
                            <h3>Профиль</h3>
                        </div>
                    </div>
                    <div class="card-body">
                        <form method="post" enctype="multipart/form-data">
                            {% csrf_token %}
                            {{ form.as_p }}
                            <button type="submit" class="btn btn-outline-primary float-right">
                                Сохранить
                            </button>
                        </form>
                    </div>
                    <div class="card-footer mx-auto">
                        <a href="{% url 'users:generate_new_password' %}" class="btn btn-outline-primary">
                            Сгенерировать пароль
                        </a>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

users/templates/users/verified_sent.html
{% extends 'catalog/base.html' %}
{% load my_tags %}
{% block content %}
    <div class="container">
        <div class="row mt-5">
            <div class="col-3"></div>
            <div class="col-6 mt-5">
                <div class="alert alert-info" role="alert">
                    <h4 class="alert-heading">Письмо подтверждения отправлено!</h4>
                    <p>
                        На ваш адрес электронной почты было отправлено письмо с подтверждением. Пожалуйста, проверьте
                        свою электронную почту и нажмите на ссылку подтверждения, чтобы завершить регистрацию.
                        Если письмо не пришло, проверьте папку спам.
                    </p>
                </div>
            </div>
        </div>
    </div>
{% endblock %}