catalog/urls.py
from django.urls import path
from django.views.decorators.cache import cache_page, never_cache

from catalog.apps import CatalogConfig
from catalog.views import ContactInfo, ProductDetailView, ProductListView, ProductCreateView, BlogListView, \
    BlogDetailView, BlogCreateView, BlogUpdateView, BlogDeleteView, ProductUpdateView, ProductDeleteView

app_name = CatalogConfig.name

urlpatterns = [
    path('contact/', ContactInfo.as_view(), name='contact_info'),
]

product_urlpatterns = [
    path('', ProductListView.as_view(), name='product_list'),
    path('product/<int:pk>/', cache_page(60)(ProductDetailView.as_view()), name='product_detail'),
    path('product/create/', never_cache(ProductCreateView.as_view()), name='create_product'),
    path('product/update/<int:pk>/', never_cache(ProductUpdateView.as_view()), name='product_update'),
    path('product/delete/<int:pk>/', ProductDeleteView.as_view(), name='product_delete'),
]

blog_urlpatterns = [
    path('blog/', BlogListView.as_view(), name='blog_list'),
    path('blog/create/', never_cache(BlogCreateView.as_view()), name='blog_create'),
    path('blog/<slug:slug>/', BlogDetailView.as_view(), name='blog_detail'),
    path('blog/edit/<slug:slug>/', never_cache(BlogUpdateView.as_view()), name='blog_update'),
    path('blog/delete/<slug:slug>/', BlogDeleteView.as_view(), name='blog_delete'),
]

urlpatterns += product_urlpatterns + blog_urlpatterns

config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('catalog.urls', namespace='catalog')),
    path('user/', include('users.urls', namespace='users')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/urls.py
from django.urls import path

from users.apps import UsersConfig
from users.views import LoginView, LogoutView, RegisterView, VerifiedSentView, verify_email, ProfileView, \
    generate_new_password

app_name = UsersConfig.name

urlpatterns = [
    path('login/', LoginView.as_view(), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('register/', RegisterView.as_view(), name='register'),
    path('register/verified_sent/', VerifiedSentView.as_view(), name='verified_sent'),
    path('verify_email/<str:uidb64>/<str:token>/', verify_email, name='verify_email'),
    path('profile', ProfileView.as_view(), name='profile'),
    path('profile/genpassword', generate_new_password, name='generate_new_password'),
]

catalog/models.py
from django.conf import settings
from django.db import models

NULLABLE = {'null': True, 'blank': True}


class Product(models.Model):
    name = models.CharField(max_length=50, verbose_name='наименование')
    title = models.TextField(**NULLABLE, verbose_name='описание')
    preview = models.ImageField(upload_to='catalog/', **NULLABLE, verbose_name='изображение')
    category = models.ForeignKey('Category', verbose_name='категория', on_delete=models.CASCADE)
    price = models.FloatField(verbose_name='цена за покупку')
    creation_date = models.DateTimeField(auto_now_add=True, verbose_name='дата создания')
    last_change_date = models.DateTimeField(auto_now_add=True, verbose_name='дата последнего изменения')

    is_published = models.BooleanField(default=False, verbose_name='признак публикации')

    owner = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.SET_NULL, **NULLABLE, verbose_name='владелец')

    def __str__(self):
        return f'{self.category} {self.name}({self.title}) {self.price}'

    class Meta:
        verbose_name = 'товар'
        verbose_name_plural = 'товары'
        permissions = [
            ('set_is_published', 'Can publish posts'),
            ('set_title', 'Can change title'),
            ('set_category', 'Can change category'),
        ]


class Category(models.Model):
    name = models.CharField(max_length=50, verbose_name='наименование')
    title = models.TextField(**NULLABLE, verbose_name='описание')

    def __str__(self):
        return f'{self.name}'

    class Meta:
        verbose_name = 'категория'
        verbose_name_plural = 'категории'


class Contacts(models.Model):
    phone = models.CharField(max_length=20, verbose_name='телефон')
    telegram = models.CharField(max_length=50, verbose_name='телеграмм')
    vk = models.CharField(max_length=50, verbose_name='ВКонтакте')

    def __str__(self):
        return f'{self.phone} {self.telegram} {self.vk}'

    class Meta:
        verbose_name = 'контакт'
        verbose_name_plural = 'контакты'


class Blog(models.Model):
    title = models.CharField(max_length=50, verbose_name='заголовок')
    slug = models.CharField(max_length=50, verbose_name='slug', **NULLABLE)
    body = models.TextField(verbose_name='содержимое')
    preview = models.ImageField(upload_to='blog/', verbose_name='изображение', **NULLABLE)
    date_create = models.DateField(verbose_name='дата создания')
    is_published = models.BooleanField(default=True, verbose_name='признак публикации')
    count_views = models.IntegerField(default=0, verbose_name='количество просмотров')

    def __str__(self):
        return f'{self.title}'

    class Meta:
        verbose_name = 'публикация'
        verbose_name_plural = 'публикации'


class Version(models.Model):
    product = models.ForeignKey(Product, on_delete=models.CASCADE, verbose_name='продукт')
    version_number = models.CharField(max_length=20, verbose_name='номер версии')
    version_name = models.CharField(max_length=50, verbose_name='название версии')
    is_active = models.BooleanField(verbose_name='признак текущей версии')

    def __str__(self):
        return f'{self.version_name}({self.version_number})'

    class Meta:
        verbose_name = 'версия'
        verbose_name_plural = 'версии'

catalog/forms.py
from django import forms
from django.forms import BaseInlineFormSet

from catalog.models import Product, Version


class StyleFormMixin:

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'form-control'


class ProductForm(StyleFormMixin, forms.ModelForm):
    BANWORD = ['казино', 'криптовалюта', 'крипта', 'биржа', 'дешево', 'бесплатно', 'обман', 'полиция', 'радар']

    class Meta:
        model = Product
        exclude = ('owner', 'creation_date', 'last_change_date')

    def clean_name(self):
        cleaned_data = self.cleaned_data.get('name')
        if cleaned_data in ProductForm.BANWORD:
            raise forms.ValidationError('Присутствуют запрещенные слова в названии')
        return cleaned_data

    def clean_title(self):
        cleaned_data = self.cleaned_data.get('title')
        if cleaned_data in ProductForm.BANWORD:
            raise forms.ValidationError('Присутствуют запрещенные слова в описании')
        return cleaned_data


class VersionForm(StyleFormMixin, forms.ModelForm):

    class Meta:
        model = Version
        fields = '__all__'

catalog/views.py
from django.conf import settings
from django.contrib.auth.mixins import PermissionRequiredMixin
from django.core.mail import send_mail
from django.forms import inlineformset_factory
from django.http import Http404
from django.shortcuts import redirect
from django.urls import reverse_lazy, reverse
from django.views.generic import ListView, DetailView, CreateView, UpdateView, DeleteView, TemplateView
from pytils.translit import slugify

from catalog.forms import ProductForm, VersionForm
from catalog.models import Product, Contacts, Blog, Version
from catalog.services import get_cached_category_list


class ProductListView(ListView):
    model = Product

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = "Главная Safyro's Market"
        category_list = get_cached_category_list()
        context['category_list'] = category_list
        return context


class ProductDetailView(DetailView):
    model = Product

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        product_name = context['object'].name
        context['title'] = f"{product_name} Safyro's Market"
        return context


class ProductCreateView(CreateView):
    model = Product
    form_class = ProductForm

    def get_success_url(self):
        return reverse('catalog:product_detail', args=[self.object.pk])

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = f"Создание товара Safyro's Market"
        return context

    def form_valid(self, form):
        self.object = form.save()
        self.object.owner = self.request.user
        self.object.save()

        return super().form_valid(form)


class ProductUpdateView(UpdateView):
    model = Product
    form_class = ProductForm

    def get_object(self, queryset=None):
        self.object = super().get_object(queryset)
        if self.object.owner != self.request.user and not self.request.user.has_perm(f'catalog.set_is_published'):
            raise Http404
        return self.object

    def get_success_url(self):
        return reverse('catalog:product_detail', args=[self.kwargs.get('pk')])

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = f"Редактирование товара {self.object.title} Safyro's Market"

        SubjectFormset = inlineformset_factory(Product, Version, form=VersionForm, extra=1)
        if self.request.method == 'POST':
            context['formset'] = SubjectFormset(self.request.POST, instance=self.object)
        else:
            context['formset'] = SubjectFormset(instance=self.object)

        return context

    def get_form(self, form_class=None):
        form = super().get_form(form_class)
        if self.object.owner != self.request.user:
            product_fields = [f for f in form.fields.keys()]
            for field in product_fields:
                if not self.request.user.has_perm(f'catalog.set_{field}'):
                    del form.fields[field]
        else:
            del form.fields['is_published']
        return form

    def form_valid(self, form):
        formset = self.get_context_data()['formset']
        self.object = form.save()
        if formset.is_valid():
            formset.instance = self.object
            formset.save()

        return super().form_valid(form)


class ProductDeleteView(DeleteView):
    model = Product
    success_url = reverse_lazy('catalog:product_list')

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = f"Удаление товара {self.object.title} Safyro's Market"
        return context

    def get_object(self, queryset=None):
        self.object = super().get_object(queryset)
        if self.object.owner != self.request.user and not self.request.user.has_perm(f'catalog.set_is_published'):
            raise Http404
        return self.object


class ContactInfo(TemplateView):
    template_name = 'catalog/contact_info.html'

    def get_context_data(self, **kwargs):
        context_data = super().get_context_data(**kwargs)
        context_data['object'] = Contacts.objects.first()
        context_data['title'] = "Контакты Safyro's Market"
        return context_data

    def post(self, request, *args, **kwargs):
        name = request.POST.get('name')
        email = request.POST.get('email')
        message = request.POST.get('message')
        print(f"{name}({email}):{message}")
        return redirect('catalog:contact_info')


class BlogListView(ListView):
    model = Blog

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = f"Новости Safyro's Market"
        return context

    def get_queryset(self):
        queryset = super().get_queryset()
        queryset = queryset.filter(is_published=True)
        return queryset


class BlogDetailView(DetailView):
    model = Blog

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        blog_title = context['object'].title
        context['title'] = f"{blog_title} Safyro's Market"
        return context

    def get_object(self, queryset=None):
        self.object = super().get_object(queryset)
        self.object.count_views += 1

        if self.object.count_views == 100:
            self.send_mail()

        self.object.save()
        return self.object

    def send_mail(self):
        subject = f"Пост {self.object.title} достиг 100 просмотров"
        message = 'Поздравляем!!!'
        from_email = settings.EMAIL_HOST_USER
        recipient_list = ['vektorn1212@gmail.com']

        send_mail(subject, message, from_email, recipient_list)


class BlogCreateView(CreateView, PermissionRequiredMixin):
    model = Blog
    fields = ('title', 'body', 'preview', 'date_create', 'is_published')
    permission_required = 'catalog.add_blog'
    success_url = reverse_lazy('catalog:blog_list')

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = f"Создать: Safyro's Market"
        return context

    def form_valid(self, form):
        if form.is_valid():
            new_blog = form.save()
            new_blog.slug = slugify(new_blog.title)
            new_blog.save()

        return super().form_valid(form)


class BlogUpdateView(UpdateView, PermissionRequiredMixin):
    model = Blog
    fields = ('title', 'body', 'preview', 'date_create', 'is_published', 'count_views')
    permission_required = 'catalog.change_blog'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        blog_title = context['object'].title
        context['title'] = f"Редактировать: {blog_title} Safyro's Market"
        return context

    def get_success_url(self):
        return reverse('catalog:blog_detail', args=[self.kwargs.get('pk')])

    def form_valid(self, form):
        if form.is_valid():
            new_blog = form.save()
            new_blog.slug = slugify(new_blog.title[:15])
            new_blog.save()

        return super().form_valid(form)


class BlogDeleteView(DeleteView, PermissionRequiredMixin):
    model = Blog
    permission_required = 'catalog.delete_blog'
    success_url = reverse_lazy('catalog:blog_list')

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        blog_title = context['object'].title
        context['title'] = f"Удалить: {blog_title} Safyro's Market"
        return context

catalog/templates/catalog/base.html
<!doctype html>
{% load static %}
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>{{ title }}</title>

    <link rel="canonical" href="https://getbootstrap.com/docs/4.0/examples/jumbotron/">

    <!-- Bootstrap core CSS -->
    <link href="{% static "css/bootstrap.min.css" %}" rel="stylesheet">
</head>

<body>
{% include 'catalog/include/inc_navbar.html' %}

<main role="main">
    {% block content %}
    {% endblock %}
</main>

<footer class="container text-center mt-5">
    <p>&copy; Company 2023 - {% now 'Y' %}</p>
</footer>

<!-- Bootstrap core JavaScript
================================================== -->
<!-- Placed at the end of the document so the pages load faster -->
<script src="https://code.jquery.com/jquery-3.2.1.slim.min.js"
        integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN"
        crossorigin="anonymous"></script>
<script src="{% static 'js/popper.min.js' %}"></script>
<script src="{% static 'js/bootstrap.min.js' %}"></script>
</body>
</html>

catalog/templates/catalog/blog_confirm_delete.html
{% extends 'catalog/base.html' %}
{% load my_tags %}
{% block content %}
    <div class="container">
        <div class="row mt-5">
            <div class="col-12 mt-5">
                <div class="card">
                    <div class="card-body">
                        <form method="post">
                            {% csrf_token %}
                            <p>Хотите удалить публикацию "{{ object.title }}"?</p>
                            <button type="submit" class="btn btn-danger">Подтвердить</button>
                            <a href="{% url 'catalog:blog_list' %}" class="btn btn-primary">Отмена</a>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

catalog/templates/catalog/blog_detail.html
{% extends 'catalog/base.html' %}
{% load my_tags %}
{% block content %}
    <div class="container">
        <div class="row">
            <div class="col-12 mt-5">
                <div class="card mt-3 border-light">
                    <h2 class="card-header mx-auto">{{ object.slug }}</h2>
                     <p class="card-text small">Просмотры: {{ object.count_views }}</p>
                    <div class="row">
                        <div class="col-5 m-4 mx-auto">
                            <img src="{% path_tag object.preview %}" width=450 height="280" alt=""/>
                        </div>
                        <div class="col-12">
                            <div class="card-body">
                                <p class="card-text">
                                    {{ object.body }}...
                                </p>
                            </div>
                            <p class="card-text float-right mt-4">
                                {{ object.date_create }}
                            </p>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

catalog/templates/catalog/blog_form.html
{% extends 'catalog/base.html' %}
{% load my_tags %}
{% block content %}
    <div class="container">
        <div class="row mt-5">
            <div class="col-12 mt-5">
                <div class="card">
                    <div class="card-body">
                        <form method="post" enctype="multipart/form-data">
                            {% csrf_token %}
                            {{ form.as_p }}
                            <button type="submit" class="btn btn-outline-primary float-right">
                                {% if object %}
                                    Сохранить
                                {% else %}
                                    Создать
                                {% endif %}
                            </button>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

catalog/templates/catalog/blog_list.html
{% extends 'catalog/base.html' %}
{% load my_tags %}
{% block content %}
    <!-- Main jumbotron for a primary marketing message or call to action -->
    <div class="jumbotron">
        <div class="container">
            <h1 class="display-3">Важное о главном</h1>
            {% if perms.catalog.add_blog %}
                <a href="{% url 'catalog:blog_create' %}" class="btn btn-outline-primary">Добавить публикацию</a>
            {% endif %}
        </div>
    </div>

    <div class="container">
        <header>
            <div class="pricing-header">
                <p class="fs-5 text-body-secondary">Лента новостей:</p>
            </div>
        </header>
        <div class="row">
            <div class="col-12">
                {% for object in object_list %}
                    <div class="card mt-3 border-light">
                        <h4 class="card-header">{{ object.title }}</h4>
                        <div class="row">
                            <div class="col-5 m-4">
                                <img src="{% path_tag object.preview %}" width=450 height="280" alt=""/>
                                <p class="card-text mt-1 small">Просмотры: {{ object.count_views }}</p>
                            </div>
                            <div class="col-6">
                                <div class="card-body">
                                    <p class="card-text">
                                        {{ object.body|slice:500 }}...
                                    </p>
                                    <p class="card-text">
                                        {{ object.date_create }}
                                    </p>
                                </div>
                            </div>
                        </div>
                        <div class="card-footer">
                            <div class="btn-group float-right">
                                <a href="{% url 'catalog:blog_detail' object.slug %}" type="button"
                                   class="btn btn-primary btn-outline-primary">View</a>
                                {% if perms.catalog.change_blog %}
                                    <a href="{% url 'catalog:blog_update' object.slug %}" type="button"
                                       class="btn btn-primary btn-outline-primary">Edit</a>
                                {% endif %}
                                {% if perms.catalog.delete_blog %}
                                    <a href="{% url 'catalog:blog_delete' object.slug %}" type="button"
                                       class="btn btn-primary btn-outline-danger">Delete</a>
                                {% endif %}
                            </div>
                        </div>
                    </div>
                {% endfor %}
            </div>
        </div>
    </div><!-- /container -->
{% endblock %}

catalog/templates/catalog/contact_info.html
{% extends 'catalog/base.html' %}
{% block content %}
<!-- Main jumbotron for a primary marketing message or call to action -->
<div class="jumbotron">
    <div class="container mt-3">
        <div class="row">
            <div class="col-5 mx-auto">
                <h2>Наши контакты:</h2>
                <p>
                    г. Калининград {{ object.phone }}<br>
                    (c 02:00 до 21:00)
                </p>
                <p><a class="btn btn-secondary" href="#" role="button">View details &raquo;</a></p>
            </div>
            <div class="col-5 mx-auto">
                <h2>Мы в социальных сетях:</h2>
                <p>
                    ВКонтакте - {{ object.vk }}<br>
                    Telegram - {{ object.telegram }}
                </p>
                <p><a class="btn btn-secondary" href="#" role="button">View details &raquo;</a></p>
            </div>
        </div>
    </div>
</div>

<div class="container">
    <hr>
    <div class="row">
        <div class="col-6 mx-auto">
            <div class="card">
                <div class="card-header mx-auto">
                    <h5>Оставьте заявку для обратной связи</h5>
                </div>
                <div class="card-body">
                    <form method="post">
                        {% csrf_token %}
                        <label class="col-sm-12">
                            <input type="text" name="name" class="form-control mb-2" placeholder="Имя">
                            <input type="email" name="email" class="form-control mb-2" placeholder="Email">
                            <textarea name="message" class="form-control mb-2"
                                      placeholder="Дополнительная информация"></textarea>
                        </label>
                        <input class="btn btn-primary w-100" type="submit" value="Send"/>
                    </form>
                </div>
            </div>
        </div>
    </div>
    <hr>
</div><!-- /container -->
{% endblock %}

catalog/templates/catalog/home_page.html
{% extends 'catalog/base.html' %}
{% load my_tags %}
{% block content %}
    <!-- Main jumbotron for a primary marketing message or call to action -->
    <div class="jumbotron">
        <div class="container">
            <h1 class="display-3">Добро пожаловать!</h1>
            <p>Наша компания приветствует всех, кто зашёл на сайт! Среди нашего ассортимента вам точно удастся найти
                товар, который Вы так давно искали. Мы работаем с самыми крупными иностранными поставщиками и уверены,
                в качестве и подлинности товаров. Если у вас возникнут вопросы по товару, Вы всегда сможете связаться с
                нашими менеджерами во вкладке "Контакты", заполнив простую форму. И свами свяжутся для дальнейшей
                консультации.
            </p>
            <p><a class="btn btn-primary btn-lg" href="#" role="button">Learn more &raquo;</a></p>
        </div>
    </div>

    <div class="container">
        <header>
            <div class="pricing-header p-3 pb-md-4 mx-auto">
                <p class="fs-5 text-body-secondary">Каталог товаров:</p>
            </div>
        </header>
        <div class="row">
            {% for object in object_list %}
                <div class="col-6 mt-3">
                    <div class="card">
                        <img src="{% path_tag object.preview %}" alt="..."/>
                        <div class="card-body">
                            <h5 class="card-title">{{ object.name }}</h5>
                            <p class="card-text">
                                {{ object.title|slice:100 }}...
                            </p>
                            <p class="card-text">
                                {{ object.price }} ₽
                            </p>
                            <a href="{% url 'catalog:product_page' object.pk %}" class="btn btn-primary float-right">Купить</a>
                        </div>
                    </div>
                </div>
            {% endfor %}
        </div>
    </div><!-- /container -->
{% endblock %}

catalog/templates/catalog/product_detail.html
{% extends 'catalog/base.html' %}
{% load my_tags %}
{% block content %}
    <div class="container">
        <div class="row mt-5">
            <div class="col-6">
                {% if user.is_authenticated %}
                    <a href="{% url 'catalog:product_update' object.pk %}" class="btn btn-outline-primary mt-5 mr-2">
                        Редактировать
                    </a>
                    <a href="{% url 'catalog:product_delete' object.pk %}" class="btn btn-outline-danger mt-5">
                        Удалить
                    </a>
                {% endif %}
            </div>
            <div class="col-12">
                <div class="card border-light mt-5">
                    <div class="row g-0">
                        <div class="col-6">
                            <img src="{{ object.preview|path_filter }}" alt="..." width="500" height="300"/>
                            {% if object.owner is None %}
                                <div class="text-muted">-</div>
                            {% else %}
                                <div class="text-muted">{{ object.owner }}</div>
                            {% endif %}
                        </div>
                        <div class="col-md-6">
                            <div class="card-body">
                                <h5 class="card-title">{{ object.name }}</h5>
                                <p class="card-text">{{ object.title }}</p>
                                <p class="card-text"><small
                                        class="text-body-secondary">{{ object.creation_date }}</small>
                                </p>
                                <p class="card-text">
                                    {{ object.price }} ₽
                                </p>
                                <a href="#" class="btn btn-primary float-right">Купить</a>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

catalog/templates/catalog/product_list.html
{% extends 'catalog/base.html' %}
{% load my_tags %}
{% block content %}
    <!-- Main jumbotron for a primary marketing message or call to action -->
    <div class="jumbotron">
        <div class="container">
            <h1 class="display-3">Добро пожаловать!</h1>
            <p>Наша компания приветствует всех, кто зашёл на сайт! Среди нашего ассортимента вам точно удастся найти
                товар, который Вы так давно искали. Мы работаем с самыми крупными иностранными поставщиками и уверены,
                в качестве и подлинности товаров. Если у вас возникнут вопросы по товару, Вы всегда сможете связаться с
                нашими менеджерами во вкладке "Контакты", заполнив простую форму. И свами свяжутся для дальнейшей
                консультации.
            </p>
            <p><a class="btn btn-primary btn-lg" href="#" role="button">Learn more &raquo;</a></p>
        </div>
    </div>

    <div class="container">
        {% if user.is_authenticated %}
            <a href="{% url 'catalog:create_product' %}" class="btn btn-outline-primary">Добавить товар</a>
        {% endif %}
        <header>
            <div class="pricing-header p-3 pb-md-4 mx-auto">
                <p class="fs-5 text-body-secondary">Каталог товаров:</p>
                {% for category in category_list %}
                    <li>
                        {{ category }}
                    </li>
                {% endfor %}
            </div>
        </header>
        <div class="row">
            {% for object in object_list %}
                {% if object.is_published or perms.catalog.set_is_published %}
                    <div class="col-6 mt-3">
                        <div class="card h-100">
                            <img src="{% path_tag object.preview %}" alt="..."/>
                            <div class="card-body">
                                <h5 class="card-title">{{ object.name }}</h5>
                                <p class="card-text">
                                    {{ object.title|slice:100 }}...
                                </p>
                                <p class="card-text">
                                    {{ object.price }} ₽
                                </p>
                                {% for active_version in object.version_set.all %}
                                    {% if active_version.is_active %}
                                        <p class="text-muted">
                                            Версия: {{ active_version.version_number }}
                                        </p>
                                    {% endif %}
                                {% endfor %}
                                {% if object.owner %}
                                    <p class="text-muted">Владелец: {{ object.owner }}</p>
                                {% else %}
                                    <p class="text-muted">Владелец: -</p>
                                {% endif %}
                                <li>{{ object.category }}</li>
                                <a href="{% url 'catalog:product_detail' object.pk %}"
                                   class="btn btn-primary float-right">Купить</a>
                            </div>
                        </div>
                    </div>
                {% endif %}
            {% endfor %}
        </div>
    </div><!-- /container -->
{% endblock %}